trigger:
- main  # Replace 'main' with your branch name

pool:
  name: CarAccessories
  demands:
    - Agent.Name -equals D3-PC-14

variables:
  NUGET_SCRATCH: 'C:\Temp\NuGetScratch'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    packageType: 'sdk'
    version: '6.x'  # Replace with the required .NET version
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      mkdir C:\Temp\NuGetScratch
- script: dotnet restore
  displayName: 'Restore NuGet packages'
  
- script: |
    echo "Building the application..."
    dotnet build CarAccessoriesShop.sln
  displayName: 'Build the application'

- script: |
    echo "Running tests..."
    dotnet test CarAccessoriesShop.sln
  displayName: 'Run unit tests'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'drop'
  displayName: 'Publish Build Artifacts'